### ISSUE TITLE
To do before submitting next version to CRAN

### ISSUE THREAD

**Issue by seananderson** [ss3sim/ss3sim#213]
- [ ] Give all the documentation a once over to make sure all the arguments and output are adequately described. Make sure there are examples for most functions. Ideally people sign up for chunks of 3-4 functions and go over the documentation with a fine toothed comb.
- [x] Make a call on standardizing argument names #132 . Standardizing internal argument names, e.g. `datfile` `infile` should be relatively harmless. We shouldn't be changing any of the main `change` or `sample` argument names (the ones that get called from case files) unless we properly depreciate them (transfer their value internally and issue a warning).
- [ ] Make a call on whether we want to add to the vignette about checking convergence #123 
- [x] Make a call on changing `change_e` to use a list object datfile throughout #196 (fixed with 2215c5ce3286d1403457a4c5cbf8c1f8326150a8)
- [ ] Fix all remaining known bugs #209 #210 along with any bugs we are aware of but haven't yet reported
- [ ] Make sure we can run a completely clean `R CMD check --as-cran`.
- [ ] Carefully re-read the [CRAN Repository Policy](http://cran.r-project.org/web/packages/policies.html) and make sure we comply with everything
- [ ] Run `devtools::release()`, submit via the webform, wait, and profit

Are there important bits that people would like to add to the vignette before the next release?

**Comment by colemonnahan** [comment]
The updates to sampling I worked on should really be in the vignette. That's my biggest priority if we're going to update CRAN. Kot and I made some pretty arbitrary (and executive) decisions about how to set things up and it'll be important to document that.

I haven't looked but I think updating the docs for parallelization would also be important if not done (parallel iterations and with `get_results`).

**Comment by taylori** [comment]
I don't know if ss3sim depends on changes to r4ss that occured during this
research phase, but r4ss is long overdue to be updated on CRAN so I will
attempt to go through a similar (probably less rigorous process) with that
package. I have no time this week, but maybe next week. Any sense of
timeline for the ss3sim submission?

Also, I'm not convinced that ss3sim will be a cash cow as might be
indicated by the item "submit via the webform, wait, and profit". Was that
supposed to be "submit via the webform, wait, and pray"?

**Comment by colemonnahan** [comment]
Ian: I think that'd be great to get `r4ss` updated on CRAN.

My opinion is we should try and wait until all papers are accepted. It may be that some reviewer requests a change that requires an update to the package. If we push to CRAN as soon as the last one is accepted then we know the code is finished, and we can update instructions for recreating the studies in our git pages. Realistically this probably won't be until the end of summer.

I was hoping more for "submit, wait, and graduate"....

**Comment by seananderson** [comment]
I don't think we need to wait until all the papers are accepted before we submit to CRAN. As long as the package is actively used there will always be things added to the package. Those just end up in the next version. Tying our versions to the successful acceptance of 3 papers every time seems like a fairly ambitious goal. The big wave of modifications is over for a while at least. But, I'm fine waiting too.

![cashcow](https://cloud.githubusercontent.com/assets/19349/8171817/f8f4ec98-136f-11e5-97b0-75818d40edfa.jpg)

**Comment by colemonnahan** [comment]
I disagree that it's am ambitious goal for *this round* -- I think it's natural.  They're all in the same special issue and were developed simultaneously, so to me they should be tied to the same version. I would like to avoid having the empirical paper use a github version while the other two use CRAN.

That being said, I agree it's not feasible or desirable moving forward. Future papers (if they exist) likely will use their own git version anyway.
